export const SERVICES = [
  {
    id: 'geological',
    title: 'Geological Mapping',
    shortDescription: 'Comprehensive bedrock and surface geology mapping using field surveys and modern analytical tools.',
    description: 'We deliver systematic geological mapping programs that characterize rock types, structures, and mineralization across project areas. Our teams integrate traditional field techniques with modern remote-sensing data for unmatched accuracy.',
    icon: 'Layers',
    color: 'cyan',
    image: '/images/mineral-exploration/mineral-01.jpg',
    technologies: ['ArcGIS Pro', 'QGIS', 'MapInfo', 'Leapfrog Geo', 'Micromine'],
    deliverables: ['Geological maps (1:5,000 to 1:100,000)', 'Cross-sections & 3D models', 'Structural analysis reports', 'Mineralization maps'],
    process: ['Desk study & data compilation', 'Field mapping campaign', 'Sampling & analysis', 'Data integration & modeling', 'Final report & GIS deliverables'],
  },
  {
    id: 'geophysics',
    title: 'Geophysical Surveys',
    shortDescription: 'Ground and airborne geophysical surveys including VES, ERT, IP, EM, magnetics, and seismic methods.',
    description: 'Our geophysics team designs and executes multi-method surveys tailored to specific exploration and engineering objectives. We deliver processed, interpreted data in industry-standard formats.',
    icon: 'Activity',
    color: 'copper',
    image: '/images/ves-ert/ves-01.jpg',
    technologies: ['EMIT Maxwell', 'Oasis Montaj', 'Surfer', 'ReflexW', 'Res2DInv'],
    deliverables: ['Geophysical survey grids', 'Processed anomaly maps', 'Inversion models', 'Target priority lists'],
    process: ['Survey design & planning', 'Equipment mobilization', 'Data acquisition', 'Processing & enhancement', 'Integrated interpretation'],
  },
  {
    id: 'remote-sensing',
    title: 'Remote Sensing',
    shortDescription: 'Multi-spectral and hyperspectral satellite imagery analysis for lithological and alteration mapping.',
    description: 'Leveraging Sentinel, Landsat, ASTER, and WorldView imagery alongside AI-assisted classification, we extract maximum geological intelligence from satellite data.',
    icon: 'Globe',
    color: 'emerald',
    image: '/images/students/student-01.jpg',
    technologies: ['ENVI', 'Google Earth Engine', 'Sentinel Hub', 'ERDAS Imagine', 'ArcGIS Image Analyst'],
    deliverables: ['Lithology classification maps', 'Alteration zone maps', 'Lineament maps', 'Change detection reports'],
    process: ['Image acquisition & preprocessing', 'Spectral analysis', 'Band ratio composites', 'Machine learning classification', 'Field validation'],
  },
  {
    id: 'gis',
    title: 'GIS & Spatial Analysis',
    shortDescription: 'Advanced spatial data management, analysis, and visualization for exploration and infrastructure projects.',
    description: 'Our GIS specialists build comprehensive spatial databases, perform multi-criteria analysis, and produce publication-quality cartographic outputs for decision-makers.',
    icon: 'MapPin',
    color: 'cyan',
    image: '/images/field-operations/field-01.jpg',
    technologies: ['ArcGIS Pro', 'QGIS', 'PostGIS', 'ArcGIS Online', 'FME', 'Python (GeoPandas)'],
    deliverables: ['Geodatabases', 'Interactive web maps', 'Spatial analysis reports', 'Multi-criteria suitability maps'],
    process: ['Data inventory & QA/QC', 'Geodatabase design', 'Spatial analysis workflows', 'Visualization & web publishing', 'Training & handover'],
  },
  {
    id: 'hydro',
    title: 'Hydrogeology',
    shortDescription: 'Groundwater exploration, aquifer characterization, and water resource management studies.',
    description: 'We assess groundwater resources for mining, agriculture, urban development, and humanitarian projects through integrated hydrogeological investigations.',
    icon: 'Droplets',
    color: 'cyan',
    image: '/images/ves-ert/ves-05.jpg',
    technologies: ['MODFLOW', 'Visual MODFLOW', 'FEFLOW', 'AquaChem', 'WinLog'],
    deliverables: ['Hydrogeological maps', 'Pumping test reports', 'Groundwater models', 'Well completion reports'],
    process: ['Regional hydrogeological review', 'Geophysical profiling', 'Borehole drilling & completion', 'Aquifer testing', 'Groundwater modeling'],
  },
  {
    id: 'environmental',
    title: 'Environmental Assessment',
    shortDescription: 'Environmental impact assessments, baseline studies, and mine closure planning for regulatory compliance.',
    description: 'Our environmental team delivers comprehensive EIAs, ESIAs, and baseline surveys that satisfy international standards and national regulatory requirements.',
    icon: 'FlaskConical',
    color: 'emerald',
    image: '/images/field-operations/field-04.jpg',
    technologies: ['HEC-RAS', 'AERMOD', 'PHREEQC', 'ESRI ArcGIS', 'R / Python'],
    deliverables: ['EIA/ESIA reports', 'Environmental baseline reports', 'Monitoring programs', 'Mine closure plans'],
    process: ['Scoping & desktop study', 'Field surveys & sampling', 'Laboratory analysis', 'Impact assessment', 'Mitigation & management plans'],
  },
  {
    id: 'exploration',
    title: 'Mineral Exploration',
    shortDescription: 'End-to-end mineral exploration programs — from first-pass reconnaissance to drill-ready target delineation.',
    description: 'We design and execute systematic mineral exploration programs for gold, base metals, and industrial minerals, integrating all geoscience disciplines for highest probability drill targets.',
    icon: 'Target',
    color: 'copper',
    image: '/images/mineral-exploration/mineral-06.jpg',
    technologies: ['Leapfrog Geo', 'Micromine', 'Maptek Vulcan', 'ArcGIS Pro', 'ENVI'],
    deliverables: ['Exploration conceptual models', 'Target priority rankings', 'Drill target maps', 'Resource estimation inputs'],
    process: ['Regional targeting', 'Geochemical sampling', 'Geophysical surveys', '3D target modeling', 'Drill program design'],
  },
  {
    id: 'data',
    title: 'Data Interpretation',
    shortDescription: 'Integrated interpretation and 3D modeling of complex multi-source geoscience datasets.',
    description: 'Our data scientists and geoscientists transform raw geoscience data into actionable geological intelligence through advanced modeling, geostatistics, and machine learning.',
    icon: 'BarChart3',
    color: 'cyan',
    image: '/images/field-operations/field-02.jpg',
    technologies: ['Leapfrog Geo', 'Oasis Montaj', 'Python', 'R', 'Tableau', 'Power BI'],
    deliverables: ['3D geological models', 'Integrated interpretation reports', 'Resource estimation', 'Data dashboards'],
    process: ['Data compilation & QA/QC', 'Domain modeling', 'Statistical analysis', '3D implicit modeling', 'Resource classification'],
  },
  {
    id: 'petrophysics',
    title: 'Petrophysics',
    shortDescription: 'Rock and fluid property evaluation for reservoir, aquifer, and geotechnical decision-making.',
    description: 'We integrate well logs, core data, laboratory measurements, and geological context to estimate porosity, permeability, saturation, lithology, and reservoir quality with defensible uncertainty ranges.',
    icon: 'BarChart3',
    color: 'cyan',
    image: '/images/ves-ert/ves-11.jpg',
    technologies: ['Techlog', 'Interactive Petrophysics', 'Python', 'Petrel', 'Core analysis workflows'],
    deliverables: ['Petrophysical interpretation reports', 'Porosity and saturation models', 'Net pay summaries', 'Log quality control'],
    process: ['Data audit and conditioning', 'Lithology and fluid typing', 'Porosity and saturation modeling', 'Cross-plot analysis', 'Reservoir quality reporting'],
  },
  {
    id: 'reservoir-basin',
    title: 'Reservoir Basin Evaluation & Modeling',
    shortDescription: 'Integrated basin, reservoir, and play evaluation for oil, gas, and subsurface resource projects.',
    description: 'We evaluate basin architecture, stratigraphy, source-reservoir-seal systems, migration pathways, and reservoir distribution to support exploration screening and development planning.',
    icon: 'Globe',
    color: 'copper',
    image: '/images/mineral-exploration/mineral-11.jpg',
    technologies: ['Petrel', 'Kingdom', 'ArcGIS Pro', 'Basin modeling', 'Seismic interpretation'],
    deliverables: ['Basin evaluation reports', 'Reservoir framework models', 'Play fairway maps', 'Prospect risk summaries'],
    process: ['Regional data compilation', 'Stratigraphic framework building', 'Reservoir characterization', 'Play assessment', 'Model delivery and review'],
  },
  {
    id: 'pipeline-corrosivity',
    title: 'Pipeline Corrosivity Survey',
    shortDescription: 'Corrosivity, soil, groundwater, and route-risk surveys for pipeline integrity and infrastructure planning.',
    description: 'We assess subsurface and environmental conditions that influence external corrosion risk, helping operators prioritize mitigation, cathodic protection, and route design decisions.',
    icon: 'Activity',
    color: 'emerald',
    image: '/images/field-operations/field-09.jpg',
    technologies: ['Soil resistivity', 'pH testing', 'Redox potential', 'GIS route mapping', 'Corrosion risk ranking'],
    deliverables: ['Corrosivity maps', 'Pipeline route risk report', 'Soil and groundwater results', 'Mitigation recommendations'],
    process: ['Route review', 'Field sampling and resistivity testing', 'Laboratory analysis', 'Risk classification', 'Integrity recommendations'],
  },
  {
    id: 'oil-gas',
    title: 'Oil & Gas Services',
    shortDescription: 'Subsurface, environmental, geotechnical, and operational support for oil and gas projects.',
    description: 'We support upstream and midstream teams with integrated geoscience, site investigation, environmental baseline, route survey, and technical reporting services.',
    icon: 'Target',
    color: 'copper',
    image: '/images/field-operations/field-07.jpg',
    technologies: ['Seismic data review', 'Well log analysis', 'GIS', 'HSE workflows', 'Technical reporting'],
    deliverables: ['Subsurface studies', 'Route and site reports', 'Environmental support documents', 'Operational risk summaries'],
    process: ['Project scoping', 'Data review', 'Field and desktop studies', 'Integrated interpretation', 'Decision-ready reporting'],
  },
  {
    id: 'geotechnics',
    title: 'Geotechnics',
    shortDescription: 'Engineering geology, soil investigation, foundation studies, and ground-condition assessment.',
    description: 'We deliver practical geotechnical intelligence for buildings, roads, industrial sites, pipelines, and energy infrastructure by combining field investigation with engineering interpretation.',
    icon: 'Layers',
    color: 'cyan',
    image: '/images/field-operations/field-08.jpg',
    technologies: ['SPT/CPT support', 'Trial pits', 'Laboratory testing', 'Slope assessment', 'Geotechnical GIS'],
    deliverables: ['Geotechnical investigation reports', 'Foundation recommendations', 'Ground risk maps', 'Laboratory test summaries'],
    process: ['Desk study', 'Site reconnaissance', 'Ground investigation', 'Laboratory testing', 'Engineering assessment'],
  },
  {
    id: 'onshore-offshore',
    title: 'Onshore & Offshore Support',
    shortDescription: 'Integrated project support for land, swamp, nearshore, and offshore technical operations.',
    description: 'We provide planning, survey, geoscience, environmental, and reporting support for complex terrain and marine-influenced projects where logistics and data quality both matter.',
    icon: 'MapPin',
    color: 'emerald',
    image: '/images/field-operations/field-06.jpg',
    technologies: ['Marine and land GIS', 'Route planning', 'Field logistics', 'Environmental baseline', 'Remote sensing'],
    deliverables: ['Site support reports', 'Route and access maps', 'Baseline survey outputs', 'Operational planning briefs'],
    process: ['Logistics scoping', 'Desktop and field planning', 'Survey support', 'Data integration', 'Operational reporting'],
  },
  {
    id: 'geochemical-analysis',
    title: 'Geochemical Analysis',
    shortDescription: 'Sampling design, assay interpretation, anomaly detection, and geochemical targeting support.',
    description: 'We help clients turn rock, soil, stream sediment, and water chemistry into meaningful exploration and environmental decisions through rigorous QA/QC and multivariate interpretation.',
    icon: 'FlaskConical',
    color: 'emerald',
    image: '/images/mineral-exploration/mineral-12.jpg',
    technologies: ['ICP-MS/ICP-OES workflows', 'QA/QC charts', 'ioGAS', 'Python/R', 'GIS interpolation'],
    deliverables: ['Geochemical anomaly maps', 'Assay QA/QC reports', 'Pathfinder analysis', 'Sampling recommendations'],
    process: ['Sampling plan design', 'Field collection protocol', 'Laboratory coordination', 'QA/QC review', 'Anomaly interpretation'],
  },
  {
    id: 'regulatory',
    title: 'Regulatory Support',
    shortDescription: 'Expert support for mining license applications, environmental permitting, and regulatory compliance.',
    description: 'We guide clients through complex regulatory environments across African and international jurisdictions, preparing technical documentation that satisfies government and IFC requirements.',
    icon: 'FileText',
    color: 'copper',
    image: '/images/conferences/conf-03.jpg',
    technologies: ['GIS documentation', 'Database management', 'Report writing', 'Stakeholder engagement'],
    deliverables: ['Mining license applications', 'EIA/ESIA documents', 'Compliance audits', 'Stakeholder reports'],
    process: ['Regulatory landscape review', 'Gap analysis', 'Document preparation', 'Regulatory liaison', 'Compliance monitoring'],
  },
];

export const PROJECTS = [
  {
    id: 'west-africa-gold',
    title: 'West Africa Gold Exploration Program',
    category: 'Exploration',
    region: 'Burkina Faso, West Africa',
    client: 'Junior Mining Company',
    year: '2024',
    duration: '18 months',
    area: '450 km²',
    technologies: ['Geological Mapping', 'IP/EM Surveys', 'Geochemistry', 'Remote Sensing'],
    outcomes: ['12 priority drill targets identified', '3 new structural corridors defined', 'Resource estimate: 800,000 oz Au Inferred'],
    description: 'Systematic first-pass to advanced-stage exploration program over a greenfields gold project in the Birimian Supergroup terrane.',
    image: '/images/mineral-exploration/mineral-08.jpg',
    featured: true,
  },
  {
    id: 'urban-groundwater',
    title: 'Urban Groundwater Assessment — Lagos Metro',
    category: 'Hydrogeology',
    region: 'Lagos, Nigeria',
    client: 'Lagos State Government',
    year: '2024',
    duration: '8 months',
    area: '180 km²',
    technologies: ['Electrical Resistivity', 'Hydrogeology', 'GIS', 'Hydrochemistry'],
    outcomes: ['32 optimal borehole sites identified', 'Aquifer vulnerability map produced', 'Safe yield: 15,000 m³/day'],
    description: 'Comprehensive groundwater potential assessment to support sustainable water supply for over 2 million urban residents.',
    image: '/images/ves-ert/ves-03.jpg',
    featured: true,
  },
  {
    id: 'copper-geophysics',
    title: 'Copper Porphyry IP Survey',
    category: 'Geophysics',
    region: 'Democratic Republic of Congo',
    client: 'Mid-tier Mining Company',
    year: '2023',
    duration: '4 months',
    area: '80 km²',
    technologies: ['IP/Resistivity', 'Magnetics', '3D Inversion', 'Data Interpretation'],
    outcomes: ['Porphyry-style IP anomaly defined', '3D inversion model delivered', 'Priority drill target: 1.2 km × 800 m'],
    description: 'Detailed induced polarization survey over a copper porphyry exploration target in the Central African Copperbelt.',
    image: '/images/ves-ert/ves-07.jpg',
    featured: false,
  },
  {
    id: 'eia-iron-ore',
    title: 'Iron Ore Mine EIA — Kogi State',
    category: 'Environmental',
    region: 'Kogi State, Nigeria',
    client: 'Infrastructure Developer',
    year: '2023',
    duration: '6 months',
    area: '120 km²',
    technologies: ['Environmental Baseline', 'GIS', 'Hydrology', 'Stakeholder Engagement'],
    outcomes: ['Full ESIA report approved', 'Environmental management plan', 'Community benefit-sharing framework'],
    description: 'Full environmental and social impact assessment for a proposed iron ore mine and associated infrastructure project.',
    image: '/images/field-operations/field-05.jpg',
    featured: false,
  },
  {
    id: 'remote-sensing-ghana',
    title: 'Multi-spectral Alteration Mapping — Ghana',
    category: 'Research',
    region: 'Ashanti Region, Ghana',
    client: 'University Research Program',
    year: '2023',
    duration: '3 months',
    area: '1,200 km²',
    technologies: ['Sentinel-2', 'ASTER', 'Google Earth Engine', 'Machine Learning'],
    outcomes: ['Hydrothermal alteration zones mapped', 'New prospective corridors identified', 'Published in peer-reviewed journal'],
    description: 'Regional hydrothermal alteration mapping using multi-spectral satellite imagery analysis and machine learning classification.',
    image: '/images/students/student-01.jpg',
    featured: false,
  },
  {
    id: 'gis-training',
    title: 'GIS for Mineral Exploration — Training Program',
    category: 'Training',
    region: 'Accra, Ghana',
    client: 'Regional Mining Authority',
    year: '2024',
    duration: '2 weeks',
    area: 'N/A',
    technologies: ['ArcGIS Pro', 'QGIS', 'Leapfrog Geo', 'Python'],
    outcomes: ['45 geologists trained', 'Online learning platform deployed', 'Certification awarded'],
    description: 'Intensive professional GIS and spatial analysis training program for government geologists and industry professionals.',
    image: '/images/conferences/conf-01.jpg',
    featured: false,
  },
];

export const STATS = [
  { label: 'Projects Completed', value: 20, suffix: '+' },
  { label: 'States Served', value: 3, suffix: '' },
  { label: 'Clients Supported', value: 10, suffix: '+' },
  { label: 'Years of Excellence', value: 5, suffix: '' },
];

export const TESTIMONIALS = [
  {
    quote: "Frandee's integrated exploration approach — combining remote sensing, geophysics, and detailed field work — helped us identify a Tier-1 gold target that's now in feasibility. Their technical quality is second to none.",
    author: 'James Thornton',
    role: 'Exploration Director, AurixMine PLC',
    image: '/images/conferences/conf-05.jpg',
  },
  {
    quote: 'The hydrogeological study Frandee delivered was exceptional — detailed, regulatory-compliant, and completed on time. Their GIS deliverables alone saved us months of internal processing work.',
    author: 'Commissioner Ngozi Eze',
    role: 'Kogi State Ministry of Water Resources',
    image: '/images/conferences/conf-07.jpg',
  },
  {
    quote: 'We engaged Frandee for a complex multi-element geochemical interpretation program. Their use of multivariate statistics and machine learning to define pathfinder anomalies was genuinely state-of-the-art.',
    author: 'Prof. Kwame Asante',
    role: 'University of Ghana — Department of Earth Science',
    image: '/images/conferences/conf-09.jpg',
  },
];
